# This file was generated by GoReleaser. DO NOT EDIT.
cask "ploy" do
  name "ploy"
  desc "Ploy - Infrastructure orchestration and deployment platform"
  homepage "https://github.com/iw2rmb/ploy"
  version "0.1.18-rc8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ploy"

  on_macos do
    on_intel do
      url "https://github.com/iw2rmb/ploy/releases/download/v#{version}/ploy_#{version}_darwin_amd64.tar.gz"
      sha256 "5bb079ec736970ab18c5508bf748d8217364c567bcea9eda3ccbd1e57bd29189"
    end
    on_arm do
      url "https://github.com/iw2rmb/ploy/releases/download/v#{version}/ploy_#{version}_darwin_arm64.tar.gz"
      sha256 "8109abbe745de7689237486b833a2f39b4f693ed71141ce749752a5b4e7d994b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/iw2rmb/ploy/releases/download/v#{version}/ploy_#{version}_linux_amd64.tar.gz"
      sha256 "81f3b0c5578c882fcbe0d7c1d710044fb36f895ba2e4aeac172b4155bbd299ef"
    end
    on_arm do
      url "https://github.com/iw2rmb/ploy/releases/download/v#{version}/ploy_#{version}_linux_arm64.tar.gz"
      sha256 "478c55ac3e616d338cfecb3e684c8e0bc927817d0476f8e77bd07f49679c2538"
    end
  end

  # No zap stanza required
end
